import type { NextPage } from "next";
import Head from "next/head";
import { ReactElement, useEffect } from "react";
import MainPage from "../components/MainPage";
import Header from "../components/Header";
import { useDispatch, useSelector } from "react-redux";
import { checkConnection, getData } from "../store/actions";
import IncorrectNetworkModal from "../components/Popups/IncorrectNetworkModal";
import { RootState } from "../store/reducers";

const Home: NextPage = (): ReactElement => {
  const dispatch = useDispatch();

  const connected = useSelector((state: RootState) => state.connected);

  useEffect(() => {
    dispatch(checkConnection());

    if (connected) {
      setTimeout(() => {
        dispatch(getData());
      }, 1);
    }
  }, [connected]);

  const isCorrectNetwork = useSelector(
    (state: RootState) => state.isCorrectNetwork
  );

  return (
    <>
      <Head>
        <link rel="icon" href="./favicon.svg" />
        <title>RMZ</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      {!isCorrectNetwork && <IncorrectNetworkModal />}
      <Header />
      <MainPage />
    </>
  );
};

export default Home;
